version: "3.7"
services:
  cayley:
    image: cayleygraph/cayley
    command: http --db mongo --dbpath mongodb://mongo:27017
    ports:
      - 64210:64210
  mongo:
    image: mongo
    ports:
      - 27017:27017
  mongo_express:
    image: mongo-express:latest
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
    ports:
      - 8081:8081
    links:
      - mongo

