version: '3.7'
services:
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - mynet
  mongo_express:
    image: mongo-express:latest
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
    ports:
      - 8081:8081
    links:
      - db
    networks:
      - mynet
#  graph:
#    image: cayleygraph/cayley:latest
#    build: .
#    ports:
#      - 64210:64210
#    volumes:
#      - ./data:/data
#    links:
#      - db
#    entrypoint: ["cayley", "http", "--host=:64210", "-c data/cayley.yml"] 
#    command: ["cayley", "http", "--host=:64210", "-d mongo", "-a 0.0.0.0:27017"] 
volumes:
  mongodb_data:
#  data:
networks:
  mynet:
